### ISSUE TITLE
阿里云直链导出还会更新吗?

### ISSUE THREAD

**Issue by tpy2f0** [invobzvr/invotoys.js#10]
你好,请问一下阿里云直链导出还会更新吗?

**Comment by invobzvr** [comment]
会的。由于时间和设备限制，目前基本功能也正常，因此近期没有更新的计划

**Comment by tpy2f0** [comment]
> 会的。由于时间和设备限制，目前基本功能也正常，因此近期没有更新的计划

你好，我试了一下无法用aria2下载，你这边是正常的吗？
