### ISSUE TITLE
[aria2] (aliyundrive) please support https Scheme

### ISSUE THREAD

**Issue by tofuliang** [invobzvr/invotoys.js#2]
https://github.com/invobzvr/invotoys.js/blob/8c3eed0f01f56829e9b76bf7f5c4fd4fe723fbf2/aliyundrive/source.user.js#L181

**Comment by tofuliang** [comment]
https://github.com/invobzvr/invotoys.js/blob/8c3eed0f01f56829e9b76bf7f5c4fd4fe723fbf2/aliyundrive/source.user.js#L168

```javascript
out: ii.name,
```
set filename as well?

**Comment by invobzvr** [comment]
Updated. Right-click aria2 download button to configure default value.
